name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * 6"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.9.2-focal
    container: ${{ matrix.image }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
  nextstep:
    runs-on: macos-13
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
